### ISSUE TITLE
plot on remove server: window doesn't open

### ISSUE THREAD

**Issue by Niloofar-Alaei** [cecileane/PhyloPlots.jl#14]
Hi 

I want to do network analyses for my dataset. 

I am working on the server (EVE), and I install both packages, "PhyloNetworks" and "PhyloPlots" in julia. 

when I type: 
>using PhyloNet
the julia doesn't complain, 

and when I type plot, it shows me:  
 
>plot (generic function with 11 methods)

Everything looks good, but when I use the plot (e.g., plot(genetrees[3], :R);), it doesn't show me anything, no result, no error,.....  

Is it possible that the plot doesn't work on the server? 

Would you please let me have your idea to solve my problem? 

With the best 
Niloo

**Comment by cecileane** [comment]
If you see the julia prompt after your run the `plot` command (and see no error), then the command worked. So the problem is with not being able to see the new window. You need your local machine to give permission to the server to open (and control) a new local window, and your server needs to be told how to open a window on your local machine. That's often quite hard, and it's doesn't work.

I suggest that you install julia on your local machine, and run your plots locally: not on your remote server. It also means that you will need to copy your network files from the server to your local machine. This approach makes sense for things that are interactive and that don't require heavy computational work, like plotting, re-rooting, etc. I hope this approach works for you.

**Comment by Niloofar-Alaei** [comment]
Thanks  a lot for your help


Now I  install julia on my local machine and test the example file and it works.


With the best

Niloo


________________________________
